<template>
  <div 
    v-if="modelValue" 
    class="fixed inset-0 bg-black bg-opacity-75 z-50 flex items-start justify-center pt-8 p-4"
    @click.self="closeModal"
  >
    <div class="relative mx-auto border border-gray-600 shadow-lg rounded-xl bg-card max-h-[90vh] overflow-y-auto" style="width: 480px;">
      <div class="p-5">
        <h3 class="text-lg font-medium text-primary mb-4">
          {{ t('clients.addNewClient') }}
        </h3>
        <form @submit.prevent="saveClient">
          <div class="space-y-4">
            <div>
              <label class="block text-sm font-medium text-secondary">{{ t('clients.fullName') }}</label>
              <input
                v-model="clientForm.full_name"
                type="text"
                required
                class="mt-1 block w-full px-3 py-2 border border-gray-600 bg-hover text-primary rounded-md focus:outline-none focus:ring-accent focus:border-accent"
              />
            </div>
            <div>
              <label class="block text-sm font-medium text-secondary">{{ t('clients.email') }}</label>
              <input
                v-model="clientForm.email"
                type="email"
                class="mt-1 block w-full px-3 py-2 border border-gray-600 bg-hover text-primary rounded-md focus:outline-none focus:ring-accent focus:border-accent"
              />
            </div>
            <div>
              <label class="block text-sm font-medium text-secondary">{{ t('clients.phone') }}</label>
              <input
                v-model="clientForm.phone"
                type="tel"
                required
                class="mt-1 block w-full px-3 py-2 border border-gray-600 bg-hover text-primary rounded-md focus:outline-none focus:ring-accent focus:border-accent"
              />
            </div>
            <div v-if="showMembershipNumber">
              <label class="block text-sm font-medium text-secondary">{{ t('clients.membershipNumber') }}</label>
              <div class="mt-1 flex items-center">
                <input
                  :value="nextMembershipNumber"
                  type="text"
                  readonly
                  class="block w-full px-3 py-2 border border-gray-600 bg-gray-700 text-gray-300 rounded-md cursor-not-allowed"
                />
                <span class="ml-2 text-xs text-secondary">
                  {{ t('clients.membershipAutoGenerated') }}
                </span>
              </div>
            </div>
            <div v-if="showAddress">
              <label class="block text-sm font-medium text-secondary">{{ t('clients.address') }}</label>
              <textarea
                v-model="clientForm.address"
                rows="3"
                class="mt-1 block w-full px-3 py-2 border border-gray-600 bg-hover text-primary rounded-md focus:outline-none focus:ring-accent focus:border-accent"
              ></textarea>
            </div>
          </div>
          
          <div class="flex justify-end space-x-3 mt-6">
            <button
              type="button"
              @click="closeModal"
              class="px-4 py-2 text-sm font-medium text-secondary bg-hover hover:bg-card hover:text-primary hover:scale-105 border border-gray-600 rounded-md transition-all duration-200"
            >
              {{ t('common.cancel') }}
            </button>
            <button
              type="submit"
              :disabled="saving"
              class="px-4 py-2 text-sm font-medium text-black bg-accent hover:bg-accent/80 hover:scale-105 rounded-md disabled:opacity-50 disabled:hover:scale-100 transition-all duration-200"
            >
              {{ saving ? t('clients.saving') : t('clients.create') }}
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>

  <!-- Toast Notification for Errors -->
  <div 
    v-if="error" 
    class="fixed bottom-4 left-1/2 transform -translate-x-1/2 z-50 max-w-md w-full mx-4"
  >
    <div class="bg-red-900/90 border border-red-400 text-red-100 px-4 py-3 rounded-lg shadow-lg backdrop-blur-sm">
      <div class="flex items-center justify-between">
        <div class="flex items-center">
          <svg class="h-5 w-5 text-red-400 mr-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
          </svg>
          <p class="text-sm">{{ error }}</p>
        </div>
        <button 
          @click="clearError()" 
          class="text-red-300 hover:text-red-100 hover:scale-110 ml-4 transition-all duration-200"
        >
          <svg class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, watch } from 'vue'
import { apiClient } from '../../utils/api.js'
import { useI18n } from '../../i18n/composable.ts'

const { t } = useI18n()

// Props
const props = defineProps({
  modelValue: {
    type: Boolean,
    default: false
  },
  clients: {
    type: Array,
    default: () => []
  },
  showMembershipNumber: {
    type: Boolean,
    default: false
  },
  showAddress: {
    type: Boolean,
    default: false
  }
})

// Emits
const emit = defineEmits(['update:modelValue', 'client-created'])

// Reactive data
const saving = ref(false)
const error = ref('')

const clientForm = ref({
  full_name: '',
  email: '',
  phone: '',
  address: '',
  is_active: true
})

// Computed property to calculate next membership number
const nextMembershipNumber = computed(() => {
  if (props.clients.length === 0) return '0001'
  
  // Get all existing membership numbers
  const existingNumbers = props.clients
    .map(client => client.membership_number)
    .filter(num => num && num.length > 0)
    .map(num => parseInt(num, 10))
    .filter(num => !isNaN(num))
  
  // Find the highest number and add 1
  const maxNumber = existingNumbers.length > 0 ? Math.max(...existingNumbers) : 0
  const nextNumber = maxNumber + 1
  
  // Format with leading zeros (4 digits)
  return nextNumber.toString().padStart(4, '0')
})

// Methods
const closeModal = () => {
  emit('update:modelValue', false)
  resetForm()
}

const resetForm = () => {
  clientForm.value = {
    full_name: '',
    email: '',
    phone: '',
    address: '',
    is_active: true
  }
  error.value = ''
}

const clearError = () => {
  error.value = ''
}

const saveClient = async () => {
  saving.value = true
  error.value = ''
  
  try {
    // Validate required fields
    if (!clientForm.value.full_name || !clientForm.value.full_name.trim()) {
      error.value = t('clients.errors.nameRequired') || 'El nombre es requerido'
      return
    }
    
    // Validate email format only if email is provided
    if (clientForm.value.email && clientForm.value.email.trim()) {
      const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
      if (!emailRegex.test(clientForm.value.email)) {
        error.value = t('clients.errors.invalidEmail') || 'El email no es válido'
        return
      }
    }
    
    if (!clientForm.value.phone || !clientForm.value.phone.trim()) {
      error.value = t('clients.errors.phoneRequired') || 'El teléfono es requerido'
      return
    }
    
    // Check for email duplicates only if email is provided
    let existingClient = null
    if (clientForm.value.email && clientForm.value.email.trim()) {
      existingClient = props.clients.find(client => {
        const clientEmail = client.email ? client.email.toLowerCase() : null
        const formEmail = clientForm.value.email.toLowerCase()
        return client.email && clientEmail === formEmail
      })
    }
    
    if (existingClient) {
      error.value = t('clients.errors.emailExists') || 'Este email ya está registrado'
      return
    }
    
    // Prepare client data
    const clientData = {
      ...clientForm.value
    }
    
    // Add membership number if required
    if (props.showMembershipNumber) {
      clientData.membership_number = nextMembershipNumber.value
    }
    
    console.log('Creating new client with data:', clientData)
    const newClient = await apiClient.createClient(clientData)
    
    // Emit the created client
    emit('client-created', newClient)
    
    closeModal()
  } catch (err) {
    console.error('Error saving client:', err)
    // Handle specific backend errors
    if (err.message.includes('Email already exists')) {
      error.value = t('clients.errors.emailExists') || 'Este email ya está registrado'
    } else {
      error.value = err.message || t('clients.errors.createFailed') || 'Error al guardar el cliente'
    }
  } finally {
    saving.value = false
  }
}

// Watch for modal close to reset form
watch(() => props.modelValue, (newValue) => {
  if (!newValue) {
    resetForm()
  }
})
</script>